name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t nadesht35/test:new -f Dockerfile.dev .
      - run: docker run -e CI=true nadesht35/test:new npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          application_name: frontend
          environment_name: frontend-env
          existing_bucket_name: elasticbeanstalk-us-east-1-968785447428
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
